### ISSUE TITLE
Client notifies as "Synced" before Znode list has completed sync

### ISSUE THREAD

**Issue by riordant** [zcoinofficial/zcoin-client#88]
I think it should only notify as "Synced!" once Znodes are also synced, though we should discuss it.

**Comment by justanwar** [comment]
In 0.0.4, client notifies as "Synced!" only after Znode list has completed sync. I think this is how it should work.

The question is should we allow non-Znode functions (such as sending of funds) before the Znode list is fully synced since the QT wallet also disallow these functions before the list synced.

**Comment by reubenyap** [comment]
Mmm well you can send funds without znodes being synced so I'm not so sure on this as Znode sync can sometimes take a while. But i think of course any znode functions should only be allowed once it's fully synced.

**Comment by qashban4** [comment]
@riordant can you double check and so we can close.
